name: Build, Push Docker Image, and Deploy
on:
  push:
    branches:
      - main  # Trigger the pipeline when code is pushed to the 'main' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu-based GitHub runner

    steps:
      # Step 1: Checkout the latest code from the repository
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout the latest code from the repository
       # Set up AWS credentials using GitHub Secrets
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "eu-west-1"  # AWS region of your environment


      # Step 2: Log in to Docker Hub using GitHub Secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v3  # Log into Docker Hub
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username stored in GitHub secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password stored in GitHub secrets
       # Set up AWS credentials using GitHub Secrets
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # AWS Access Key stored in GitHub Secrets
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # AWS Secret Key stored in GitHub Secrets
          aws-region: "eu-west-1"  # Set the AWS region as per your environment


      # Step 3: Build Docker image from repository
      - name: Build Docker image from repository
        run: |
          docker build -t soniamohan/siansawebserver-image:latest -f Dockerfile .  

      # Step 4: Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push soniamohan/siansaweb
