name: CI/CD Pipeline for EC2 Deployment

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and Push Docker Images
      - name: Build and Push Docker Image
        run: |
          docker build -t soniamohan/siansawebserver:latest .
          docker push soniamohan/siansawebserver:latest

  deploy:
    name: Pull Docker Image on EC2
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up SSH access to EC2
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
    - name: Add SSH key
      run: |
        echo "${{ secrets.EC2_SSH_PASSPHRASE }}" | ssh-add -
      env:
        SSH_ASKPASS: /usr/bin/ssh-askpass
        
    # Step 3: Pull Docker Image on EC2
    - name: Pull Docker Image on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@18.201.46.129<< 'EOF'
          echo "Logging into Docker registry (if required)..."
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          
          echo "Pulling the Docker image..."
          docker pull soniamohan/siansawebserver:latest || { echo "Docker pull failed"; exit 1; }

          echo "Stopping any existing container..."
          docker stop siansawebserver-container || echo "No container to stop"

          echo "Removing any existing container..."
          docker rm siansawebserver-container || echo "No container to remove"
          
          echo "Running the Docker container..."
          docker run -d --name siansawebserver-container -p 8080:8080 soniamohan/siansawebserver:latest || { echo "Failed to start container"; exit 1; }
        EOF
