name: Build, Push Docker Image, Commit Changes, and Deploy to AWS

on:
  push:
    branches:
      - main  # Trigger the pipeline on pushes to the 'main' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3  # Checks out the latest code from the repository

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3  # Logs into Docker Hub using credentials from secrets
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t soniamohan/siansawebserver-image:latest -f Dockerfile .

      # Step 4: Push the Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push soniamohan/siansawebserver-image:latest

      # Step 5: Commit and push any changes to GitHub
      - name: Check for changes and commit them
        run: |
          git config --global user.email "soniamohan.ie@gmail.com"
          git config --global user.name "soniamohan24"
          
          # Add and commit changes, if any
          git add .
          git commit -m "Update CI/CD pipeline configuration" || echo "No changes to commit"
          
          # Push changes using GitHub token
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/soniamohan24/siansiansaWebServer.git HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication

      # Step 6: Deploy to AWS EC2 instance using local AWS environment
      - name: Deploy to AWS EC2
        run: |
          # Ensure AWS CLI is configured (AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY should already be set in the environment)
          echo "Using AWS credentials from local environment variables"
          
          # SSH into EC2 and run deployment commands
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.AWS_SSH_PRIVATE_KEY_PATH }} ubuntu@18.201.46.129 "\
            cd /home/ubuntu/siansaWebServer && \
            git pull origin main && \
            docker-compose down && \
            docker-compose up -d"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # For testing purposes, you can export locally
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # For testing purposes, you can export locally
          AWS_REGION: "eu-west-1"
          AWS_SSH_PRIVATE_KEY_PATH: ${{ secrets.AWS_SSH_PRIVATE_KEY_PATH }}  # SSH key path to access the EC2 instance
