name: Build, Push Docker Image, and Deploy
on:
  push:
    branches:
      - main  # Trigger the pipeline when code is pushed to the 'main' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu-based GitHub runner

    steps:
      # Step 1: Checkout the latest code from the repository
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout the latest code from the repository

      # Step 2: Log in to Docker Hub using GitHub Secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v3  # Log into Docker Hub
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username stored in GitHub secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password stored in GitHub secrets

      # Step 3: Build Docker image from repository
      - name: Build Docker image from repository
        run: |
          docker build -t soniamohan/siansawebserver-image:latest -f Dockerfile .  

      # Step 4: Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push soniamohan/siansaweb
