name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        IMAGE_TAG=$(git rev-parse --short HEAD)
        docker build -t soniamohan24/siansawebserver:$IMAGE_TAG .

    - name: Push Docker image to Docker Hub
      run: |
        docker push soniamohan/siansawebserver:$IMAGE_TAG

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: us-east-1

    - name: Add EC2 host to known hosts
      run: |
        ssh-keyscan -H your-ec2-public-ip >> ~/.ssh/known_hosts

    - name: Deploy to EC2 instance
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_PRIVATE_KEY }} ubuntu@your-ec2-public-ip << 'EOF'
          docker pull soniamohan/siansawebserver:latest
          docker stop siansawebserver-container || true
          docker rm siansawebserver-container || true
          docker run -d --name siansawebserver-container -p 8080:8080 soniamohan/siansawebserver:latest
        EOF
#rrr