
name: CI/CD Pipeline for EC2 Deployment

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and Push Docker Images
      - name: Build and Push Docker Image
        run: |
          docker build -t soniamohan/siansawebserver:latest .
          docker push soniamohan/siansawebserver:latest

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Create .ssh directory
        run: |
          mkdir -p ~/.ssh

      - name: Add SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_key
          chmod 600 ~/.ssh/ec2_key

      - name: Add EC2 Host to Known Hosts
        run: |
           ssh-keyscan -H 18.201.46.129 >> ~/.ssh/known_hosts
      # Step 3: Copy deploy script from the 'scripts' folder to the .ssh directory
      - name: Copy deploy script from 'scripts' folder to .ssh
        run: |
          # Copy the deploy script to ~/.ssh directory
          cp ./scripts/deploy_docker.sh ~/.ssh/deploy_docker.sh
          chmod +x ~/.ssh/deploy_docker.sh
          # Check if the script is in the right location
          ls -al ~/.ssh/


      # Run Docker deployment script on EC2
      - name: Run Docker Deployment Script on EC2
        run: |
          ssh -i ~/.ssh/ec2_key ubuntu@18.201.46.129 "bash -s" < ~/.ssh/deploy_docker.sh