---
- name: Deploy code to AWS
  hosts: all  # Replace this with your inventory group
  become: yes
  tasks:
    - name: Pull the latest code from GitHub
      ansible.builtin.git:
        repo: 'https://github.com/soniamohan24/siansiansaWebServer.git'  # Replace with your repo URL
        dest: /home/ubuntu/siansaWebServer  # Replace with the directory on the AWS instance
        version: main  # Replace with your desired branch

    - name: Install dependencies
      ansible.builtin.shell:
        cmd: |
          cd /home/ubuntu/siansaWebServer
          pip install -r requirements.txt  # Assuming it's a Python project with dependencies
        args:
          chdir: /home/ubuntu/siansaWebServer

    - name: Restart application service
      ansible.builtin.service:
        name: docker  # Replace with the service name for your application
        state: restarted
